### PR TITLE
Fix nearby projects query for android

### LINKED ISSUE #404: Nearby tab shows no data in projects on Android
**Describe the bug**
On Android, on the Projects screen the Nearby tab does not display any projects, whereas on iOS data is displayed. This was brought up in PR https://github.com/inaturalist/iNaturalistReactNative/pull/389

**To Reproduce**
1. Go to 'Projects' screen
2. Tap on 'Nearby' tab
3. Data for projects does not change

**Expected behavior**
Data should appear in the Nearby tab, as it does on iOS.

**Additional context**
An error is thrown in the console: `Error: Fatal: TypeError: Cannot read property 'latitude' of null`

### PR DESCRIPTION
**Pull request by Chrischuck**
Mostly fixes #404 

Turns out it was just slow on Android. Updated the `useUserLocation` hook to optionally make the place guess which was causing an unnecessary  delay (both places which use `useUserLocation` do not use the place guess currently.

### CODE REVIEW

File: src/components/Projects/ProjectTabs.js [hunk 1]
```diff
@@ -29,47 +29,45 @@ const ProjectTabs = ( ): Node => {
...
-      fetchUserJoinedProjects( );
+    if ( memberId && currentTabId === JOINED_TAB_ID ) {
+      setApiParams( { member_id: memberId } );
+    } else if ( currentTabId === FEATURED_TAB_ID ) {
+      setApiParams( { features: true } );
+    } else if ( currentTabId === NEARBY_TAB_ID ) {
+      setApiParams( {
+        lat: latLng.latitude,
+        lng: latLng.longitude
+      } );
```
Comment (Chrischuck) [inline src/components/Projects/ProjectTabs.js:41]: Moved these to the `useEffect` because I found in some instances that you can be on one tab, but different data shows. Usually happened when navigating away from the projects page and back.

Now the query is a reflection of the current tab.

File: src/realmModels/Observation.js [hunk 2]
```diff
@@ -192,7 +192,7 @@ class Observation extends Realm.Object {
   }
 
   static projectUri = obs => {
-    const photo = obs.observation_photos[0];
+    const photo = obs?.observation_photos?.[0];
```
Comment (Chrischuck) [inline src/realmModels/Observation.js:195]: unrelated bug, but this was giving me undefined errors when viewing nearby projects on android

**Comment by kueda** [comment]
@Chrischuck if you're still working on this, can you mark it as a draft PR? That way we know not to review it yet.

**Comment by Chrischuck** [comment]
@kueda should be ready to review now!

File: src/components/Projects/ProjectTabs.js [hunk 3]
```diff
@@ -20,64 +21,65 @@ const ProjectTabs = ( ): Node => {
...
-
   useEffect( ( ) => {
-    if ( memberId ) {
-      fetchUserJoinedProjects( );
+    if ( memberId && currentTabId === JOINED_TAB_ID ) {
+      setApiParams( { member_id: memberId } );
+    } else if ( currentTabId === FEATURED_TAB_ID ) {
+      setApiParams( { features: true } );
+    } else if ( currentTabId === NEARBY_TAB_ID ) {
+      if ( latLng ) {
```
Comment (kueda) [inline src/components/Projects/ProjectTabs.js:40]: I think you could just add this to the `else if` above, e.g. `} else if ( currentTabId === NEARBY_TAB_ID && latLng ) {`

**Review by kueda — APPROVED** [review]
Looks good to me. My one request is cosmetic, so if you don't have time to get to that let me know and I'll just merge.
