### PR TITLE
#1429 - properly delete observation photo

### LINKED ISSUE #1429: Can't delete photo from observation
**Describe the bug**
A user should be able to delete photos via the Media Viewer, coming from the ObsEdit screen

**To Reproduce**
1. Go to ObsEdit for an observation with at least one photo
2. Tap on photo to pull up Media Viewer
3. Use trash can icon to delete photo
4. Tap discard on bottom sheet
5. Nothing happens; photo is not deleted

**Screen Recording**

https://inaturalist.slack.com/archives/C02G5AATVGA/p1713820737823759

**Additional context**

### PR DESCRIPTION
**Pull request by budowski**
Closes #1429

### CODE REVIEW

File: src/components/MediaViewer/MainMediaDisplay.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ const MainMediaDisplay = ( {
             ? (
               <View className="absolute bottom-4 right-4">
                 <TransparentCircleButton
-                  onPress={( ) => onDeletePhoto( uri )}
+                  onPress={( ) => onDeletePhoto( photo.localFilePath )}
```
Comment (kueda) [inline src/components/MediaViewer/MainMediaDisplay.js:76]: This is not going to work when trying to delete a remote photo, e.g. one that was uploaded to the website and downloaded in the app.

**Review by kueda — CHANGES_REQUESTED** [review]
Sort of works, but note the bug when trying to delete remote photos.

**Review by kueda — APPROVED** [review]
