### PR TITLE
fix : flagged comments still appears flagged after being resolved 

### LINKED ISSUE #2262: Flagged comment still appears flagged after being resolved
**Describe the bug**
Flagged comments still appear flagged after being resolved.

**To Reproduce**
1. View https://www.inaturalist.org/observations/245155834 in the app
2. The comment by alr1243 shows an orange flag and the label "Flagged"
3. View https://www.inaturalist.org/observations/245155834 on the web to confirm there are no open flags

**Expected behavior**
If a comment (or ID) has flags but they are all resolved, it should not appear flagged.

**Screenshots**
IMG_2231

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: 17.6.1
 - App version: 0.50.0

**Additional context**
The flagged state should only appear if there are any unresolved flags on the comment or ID.

### PR DESCRIPTION
**Pull request by israr002**
closes #2262

### CODE REVIEW

File: src/components/ObsDetails/ActivityTab/ActivityHeaderContainer.js [hunk 1]
```diff
@@ -35,19 +35,21 @@ const ActivityHeaderContainer = ( {
...
   useEffect( ( ) => {
     const isActiveUserTheCurrentUser = async ( ) => {
       const current = await isCurrentUser( user?.login );
       setCurrentUser( current );
     };
     isActiveUserTheCurrentUser( );
+  }, [user] );
 
-    if ( numFlags > 0 ) {
+  useEffect( ( ) => {
```
Comment (albullington) [inline src/components/ObsDetails/ActivityTab/ActivityHeaderContainer.js:48]: We really don't want to use `useEffects` in code unless they're absolutely necessary, since they cause extra rerenders. In this case, you've already made `isFlagged` into a boolean, so there's no need for this line `const [flagged, setFlagged] = useState( false )` and there's no need for this effect. I'd remove both and rename `isFlagged` to `flagged`.

**Review by albullington — CHANGES_REQUESTED** [review]

**Review by albullington — APPROVED** [review]
